# Generated by Django 5.1.2 on 2024-11-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_model_registry', '0005_alter_modelmetadata_feature_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelmetadata',
            name='api_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
