# Generated by Django 5.1.2 on 2024-10-13 20:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_store_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.JSONField(blank=dict, default=dict)),
                ('feature_id', models.BigIntegerField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('feature_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feature_service.featurestore')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=250)),
                ('feature_description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('feature_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feature_service.featurestore')),
            ],
        ),
    ]
