# Generated by Django 5.1.2 on 2024-10-24 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature_service', '0002_featuremetadata_data_source_featuremetadata_datatype'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='featuremetadata',
            unique_together={('feature_name', 'feature_store')},
        ),
    ]
