# Generated by Django 5.1.2 on 2024-11-02 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature_service', '0003_alter_featuremetadata_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='features',
            old_name='feature_id',
            new_name='entity_id',
        ),
    ]
